### ISSUE TITLE
Content sniffing issues

### ISSUE THREAD

**Issue by chmln** [ebassi/xdg-mime-rs#13]
Hey @ebassi 

I'm attempting to migrate to this crate for handlr.
Having some issues with content type detection using `get_mime_type_for_data`. 

![image](https://user-images.githubusercontent.com/11352152/82721835-2c8e4880-9c8f-11ea-9383-8cceaf6ec555.png)

Here's the code in question:

```rust
static SHARED_MIME_DB: Lazy<SharedMimeInfo> = Lazy::new(SharedMimeInfo::new);
pub fn from_filename(name: &str) -> Result<Mime> {
    let mimes = SHARED_MIME_DB.get_mime_types_from_file_name(&name);
    dbg!(&name, &mimes);

    match &*mimes {
        [mime_type] if mime_type == &"application/octet-stream" => {
            let buf = std::fs::read_to_string(name)?;
            let file_mimes =
                SHARED_MIME_DB.get_mime_type_for_data(buf.as_ref());
            dbg!(&buf, file_mimes);

            match SHARED_MIME_DB.get_mime_type_for_data(buf.as_ref()) {
                Some((mime, _)) => Ok(Mime(mime.to_string())),
                None => Err(Error::Ambiguous),
            }
        }
        [mime_type, ..] => Ok(Mime(mime_type.to_string())),
        &[] => Err(Error::Ambiguous),
    }
}
```

**Comment by ebassi** [comment]
The `guess_mime_types_from_file_name()` method will match only against the file name, and the MIME type from a file named "cat" (without extension) is going to be `application/octet-stream` because the glob rule for shell scripts is `*.sh`.

What you want is the `get_mime_type_for_data()` method, but that seems to have exposed an issue with the matching code for `application/x-shellscript` that I'm debugging now.

**Comment by ebassi** [comment]
Incidentally, you probably want to look at the newly added [`guess_mime_type()`](https://docs.rs/xdg-mime/0.2.0/xdg_mime/struct.SharedMimeInfo.html#method.guess_mime_type) method, which lets you specify the file name and the data, so you can guess the MIME type depending on both. For 0.3 I've also added a `path()` method to the `GuessBuilder`, which will take a full path.
