### ISSUE TITLE
Test data/filename for specific mime type(s)

### ISSUE THREAD

**Issue by veeshi** [ebassi/xdg-mime-rs#23]
A nice feature would be to test if some data or a filename is a certain mimetype or mimetypes. This way it will be performant as it will only be carrying out a check for the requested mime types and not for each mimetype.

**Comment by ebassi** [comment]
That's not really how the shared-mime-type database works.

For data blobs, the lookup operation stops at the first match; you still need to perform a tree traversal because the each magic entry can have multiple rules.

For globs—i.e. filenames—we can have multiple matching extensions, and they all have to be reported.

Do you have an example of what kind of convenience API are you looking for?

**Comment by veeshi** [comment]
Thanks, that makes sense about traversing the tree.

I'd seen a function for checking if data matched a mime type in the tree magic crate which I had been originally using however it only supports a handful of mine types.

https://docs.rs/tree_magic/0.2.3/tree_magic/fn.match_u8.html

**Comment by ebassi** [comment]
In the end, I didn't write any convenience API for this.

Using `GuessBuilder::guess()` to guess a MIME type, and then using `Mime::from_str()` to check if it's a specific MIME type is already pretty simple; if somebody wishes to implement additional convenience API, feel free to open a pull request.
